version: 2.1
jobs:
  build_latest:
    docker:
      - image: cimg/node:14.13
        auth:
          username: emilysamiibocorner
          password: $DOCKERHUB_PW
    working_directory: ~/app
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: build docker image
          command: |
            docker build -t $IMAGE_NAME:latest .
      - run:
          name: Push to DO Registry
          command: |
            echo "DO_REGISTRY_PWD" | docker login -u "$DO_REGISTRY_USER" --password-stdin registry.digitalocean.com
            docker tag "${IMAGE_NAME}:latest" "${DO_IMAGE_NAME}:latest"
            docker push "${DO_IMAGE_NAME}:latest"
      - run:
          name: Push Public Image to GCR
          command: |
            echo "${GCR_AUTH}" > "${HOME}/gcr-key.json"
            cat "${HOME}/gcr-key.json" | docker login -u _json_key --password-stdin https://gcr.io
            docker tag "${IMAGE_NAME}:latest" "${GCR_IMAGE_NAME}:latest"
            docker push "${GCR_IMAGE_NAME}:latest"
workflows:
  version: 2
  build_latest:
    jobs:
      - build_latest:
          context: docker
